version: '3.1'

services:
  db :
    image: mariadb:latest
    container_name: my-mariadb
    restart: always
    environment:
      MARIADB_USER: fidelity
      MARIADB_PASSWORD: fidelity
      MARIADB_ROOT_PASSWORD: fidelity
      MARIADB_DATABASE: fidelity
    volumes:
      - "./data/mariadb/data:/var/lib/mysql/data/"
      - "./data/mariadb/logs:/var/lib/mysql/logs/"
    ports:
      - 3306:3306
      
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1